import os
import logging
from typing import Dict, Any

from reasoning_engine import (
    detect_patterns,
    generate_summary,
    infer_root_cause,
    infer_severity,
    generate_recommendations
)

logger = logging.getLogger(__name__)

def extract_section(md_content: str, header_keyword: str) -> str:
    if not md_content:
        return ""
    lines = md_content.split('\n')
    in_section = False
    content = []
    for line in lines:
        if line.startswith('###') and header_keyword in line:
            in_section = True
            continue
        if in_section:
            if line.startswith('###'):
                break
            content.append(line)
            
    while content and not content[0].strip():
        content.pop(0)
    while content and not content[-1].strip():
        content.pop()
        
    return '\n'.join(content).strip()

def format_images(area):
    images = [img for img in area.get("images", []) if img and img != "Image Not Available"]
    if not images:
        return "Image Not Available"
    return "\n".join(
        [f"![{area.get('name', 'Area')}]({img})" for img in images[:2]]
    )

def clean_text(text):
    if not text:
        return ""
    text = text.strip()
    text = text.capitalize()
    if not text.endswith("."):
        text += "."
    return text

def generate_report(data: dict) -> str:
    md_content = data.get("full_markdown_report", "")
    patterns = detect_patterns(data)
    
    # 1. Summary
    summary = extract_section(md_content, "1. Property Issue Summary")
    if not summary or "Not Available" in summary:
        summary = generate_summary(patterns)
        
    # 3. Root Cause
    root_cause = extract_section(md_content, "3. Probable Root Cause")
    if not root_cause or "Not Available" in root_cause:
        root_cause = infer_root_cause(patterns)
        
    # 4. Severity
    severity_text = extract_section(md_content, "4. Severity Assessment")
    if not severity_text or "Not Available" in severity_text:
        level, reason = infer_severity(patterns)
        severity_text = f"* Severity Level: {level}\n* Reason: {reason}"
        
    # 5. Recommendations
    recommendations_text = extract_section(md_content, "5. Recommended Actions")
    if not recommendations_text or "Not Available" in recommendations_text:
        recs = generate_recommendations(patterns)
        if recs:
            recommendations_text = "\n".join([f"* {clean_text(r)}" for r in recs])
        else:
            recommendations_text = "* No recommended actions available."
            
    # 6. Additional Notes
    notes = extract_section(md_content, "6. Additional Notes")
    if not notes or "Generated via fallback" in notes or "placeholder" in notes.lower() or "safe report" in notes.lower():
        notes = "Automatically generated by UrbanRoof AI System. Visual evidence is strictly matched with analytical findings."
        
    # 7. Missing Info
    missing_info_text = extract_section(md_content, "7. Missing or Unclear Information")
    if not missing_info_text or "None reported" in missing_info_text:
        missing_list = data.get("missing_info", [])
        if missing_list:
            missing_info_text = "\n".join([f"* {clean_text(m)}" for m in missing_list])
        else:
            missing_info_text = "* None reported."

    lines = []
    lines.append("# Detailed Diagnostic Report\n")
    
    lines.append("### 1. Property Issue Summary")
    lines.append(f"{summary}\n")
    
    lines.append("### 2. Area-wise Observations")
    areas = data.get("areas", [])
    if not areas:
        lines.append("No area-wise observations reported.\n")
    else:
        for area in areas:
            area_name = area.get("name", "General")
            lines.append(f"Area: {area_name}\n")
            
            insp = area.get("inspection_findings", [])
            valid_insp = [f for f in insp if f and f.strip()]
            if not valid_insp:
                lines.append("* No visible findings reported.")
            else:
                for f in valid_insp:
                    lines.append(f"* {clean_text(f)}")
                    
            lines.append("\nThermal Insights:\n")
            therm = area.get("thermal_findings", [])
            valid_therm = [t for t in therm if t and t.strip()]
            if not valid_therm:
                lines.append("* Thermal data not available for this area.")
            else:
                for t in valid_therm:
                    lines.append(f"* {clean_text(t)}")
                    
            lines.append("\nImages:")
            lines.append(format_images(area))
            lines.append("")
            
    lines.append("### 3. Probable Root Cause")
    lines.append(f"{root_cause}\n")
    
    lines.append("### 4. Severity Assessment")
    lines.append(f"{severity_text}\n")
    
    lines.append("### 5. Recommended Actions")
    lines.append(f"{recommendations_text}\n")
    
    lines.append("### 6. Additional Notes")
    lines.append(f"{notes}\n")
    
    lines.append("### 7. Missing or Unclear Information")
    lines.append(f"{missing_info_text}\n")
    
    return "\n".join(lines)


class ReportGenerator:
    def __init__(self, output_dir: str = "outputs"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)
        
    def generate(self, enriched_data: Dict[str, Any], filename: str = "DDR_Report.md") -> str:
        logger.info(f"Formatting and saving final DDR report: {filename}")
        
        final_md = generate_report(enriched_data)
            
        output_path = os.path.join(self.output_dir, filename)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(final_md)
            
        logger.info(f"Report saved to {output_path}")
        return output_path
