import os
import logging
from typing import Dict, Any

from reasoning_engine import (
    detect_patterns,
    generate_summary,
    infer_root_cause,
    infer_severity,
    generate_recommendations
)

logger = logging.getLogger(__name__)

def extract_section(md_content: str, header_keyword: str) -> str:
    if not md_content:
        return ""
    lines = md_content.split('\n')
    in_section = False
    content = []
    for line in lines:
        if line.startswith('###') and header_keyword in line:
            in_section = True
            continue
        if in_section:
            if line.startswith('###'):
                break
            content.append(line)
            
    while content and not content[0].strip():
        content.pop(0)
    while content and not content[-1].strip():
        content.pop()
        
    return '\n'.join(content).strip()

def format_images(area):
    images = [img for img in area.get("images", []) if img and img.strip().lower() not in {"image not available", "image image"}]
    if not images:
        return "Image Not Available"
    return "\n".join(
        [f"![{area.get('name', 'Area')}]({img})" for img in images[:2]]
    )

def clean_text(text: str) -> str:
    if not text:
        return ""
    text = text.strip()
    words = text.split()
    if len(words) == 2 and words[0].lower() == words[1].lower():
        text = words[0]
    text = text.replace("wc", "WC area")
    text = text.replace("nahani trap/brickbat coba under", "Nahani trap or brickbat coba layer")
    text = text.replace("observed.", "observed")
    text = text.strip()
    text = text.capitalize()
    if not text.endswith("."):
        text += "."
    return text


def clean_observations(obs_list):
    cleaned = []
    seen = set()
    for o in obs_list:
        o = clean_text(o)
        if not o or len(o) < 10:
            continue
        key = o.lower()
        if key not in seen:
            cleaned.append(o)
            seen.add(key)
    return cleaned[:8]


def format_missing_info(missing_list):
    if not missing_list:
        return "* None reported."

    conflict_present = any("conflict" in str(item).lower() for item in missing_list)
    non_conflicts = [str(item).strip() for item in missing_list if item and "conflict" not in str(item).lower()]

    if conflict_present:
        lines = ["* Thermal data does not consistently confirm observed leakage across multiple areas, suggesting intermittent or concealed moisture sources."]
        if non_conflicts:
            for item in non_conflicts:
                clean_item = clean_text(item)
                if clean_item:
                    lines.append(f"* {clean_item}")
        return "\n".join(lines)

    return "\n".join([f"* {clean_text(m)}" for m in missing_list if m and str(m).strip()])


def generate_report(data: dict) -> str:
    md_content = data.get("full_markdown_report", "")
    patterns = detect_patterns(data)
    
    # 1. Summary
    summary = extract_section(md_content, "1. Property Issue Summary")
    if not summary or "Not Available" in summary:
        summary = generate_summary(patterns)
        
    # 3. Root Cause
    root_cause = extract_section(md_content, "3. Probable Root Cause")
    if not root_cause or "Not Available" in root_cause:
        root_cause = infer_root_cause(patterns)
        
    # 4. Severity
    severity_text = extract_section(md_content, "4. Severity Assessment")
    if not severity_text or "Not Available" in severity_text:
        level, reason = infer_severity(patterns)
        severity_text = f"* Severity Level: {level}\n* Reason: {reason}"
        
    # 5. Recommendations
    recommendations_text = extract_section(md_content, "5. Recommended Actions")
    if not recommendations_text or "Not Available" in recommendations_text:
        recs = generate_recommendations(patterns)
        if recs:
            recommendations_text = "\n".join([f"* {clean_text(r)}" for r in recs])
        else:
            recommendations_text = "* No recommended actions available."
            
    # 6. Additional Notes
    notes = extract_section(md_content, "6. Additional Notes")
    if not notes or "Generated via fallback" in notes or "placeholder" in notes.lower() or "safe report" in notes.lower():
        notes = "Automatically generated by UrbanRoof AI System. Visual evidence is strictly matched with analytical findings."
        
    # 7. Missing Info / Conflict Summary
    missing_info_text = format_missing_info(data.get("missing_info", []))
    if not data.get("missing_info"):
        extracted_missing = extract_section(md_content, "7. Missing or Unclear Information")
        if extracted_missing and "None reported" not in extracted_missing and "conflict" not in extracted_missing.lower():
            missing_info_text = extracted_missing

    lines = []
    lines.append("# Detailed Diagnostic Report\n")
    
    lines.append("### 1. Property Issue Summary")
    lines.append(f"{summary}\n")
    
    lines.append("### 2. Area-wise Observations")
    areas = data.get("areas", [])
    if not areas:
        lines.append("No area-wise observations reported.\n")
    else:
        for area in areas:
            area_name = area.get("name", "General")
            lines.append(f"Area: {area_name}\n")

            inspection_items = clean_observations(area.get("inspection_findings", []))
            if not inspection_items:
                lines.append("* No visible findings reported.")
            else:
                for item in inspection_items:
                    lines.append(f"* {item}")

            lines.append("\nThermal Insights:")
            thermal_items = clean_observations(area.get("thermal_findings", []))
            if not thermal_items:
                lines.append("* Thermal data not available for this area.")
            else:
                for item in thermal_items:
                    lines.append(f"* {item}")

            lines.append("\nImages:")
            lines.append(format_images(area))
            lines.append("")
            
    lines.append("### 3. Probable Root Cause")
    lines.append(f"{root_cause}\n")
    
    lines.append("### 4. Severity Assessment")
    lines.append(f"{severity_text}\n")
    
    lines.append("### 5. Recommended Actions")
    lines.append(f"{recommendations_text}\n")
    
    lines.append("### 6. Additional Notes")
    lines.append(f"{notes}\n")
    
    lines.append("### 7. Missing or Unclear Information")
    lines.append(f"{missing_info_text}\n")
    
    return "\n".join(lines)


class ReportGenerator:
    def __init__(self, output_dir: str = "outputs"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)
        
    def generate(self, enriched_data: Dict[str, Any], filename: str = "DDR_Report.md") -> str:
        logger.info(f"Formatting and saving final DDR report: {filename}")
        
        final_md = generate_report(enriched_data)
            
        output_path = os.path.join(self.output_dir, filename)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(final_md)
            
        logger.info(f"Report saved to {output_path}")
        return output_path
